agent_services: []
search_services: []
analyst_services: []
other_services:
  object_manager: false
  query_manager: true
  semantic_manager: false
sql_statement_permissions:
  - Select: true
  - Describe: true
  - Show: true
  - Unknown: false
